### ISSUE TITLE
Error : There are files newer than current files being trailed

### ISSUE THREAD

**Issue by kiranclarivate** [awslabs/amazon-kinesis-agent#134]
HI ,
COuld you please advise what can we do to deal with this error :  -
There are 26779 file(s) newer than current file(s) being trailed.

Thanks,
Kiran

**Comment by chaochenq** [comment]
How are you configuring your agent.json? Although we support matching files with filePattern in fileFlow, it's really not designed to match all the files of interest. It meant to match all the rotation of a single file. 

For example, if you have app1.log, app1.log.1, app1.log.2, app2.log, app2.log.1, app2.log2, we recommend that you create two fileFlows matching "app1.log*" and "app2.log*" separately, rather than "app*" matching everything.

**Comment by kiranclarivate** [comment]
Our agent.json has *.aws .
And it seems even with this error agent processed all the files present in the folder.So this error is not a blocker to our agent.so things look fine for now.Will get back if we find more issues related to this.
