### ISSUE TITLE
Syslog to JSON

### ISSUE THREAD

**Issue by mattford63** [awslabs/amazon-kinesis-agent#22]
Hi,

I'm completely unable to get the following config to send messages as JSON.

```
{
  "cloudwatch.emitMetrics": true,
  "kinesis.endpoint": "",
  "firehose.endpoint": "",
  "flows": [
  {
      "filePattern": "/var/log/syslog",
      "kinesisStream": "dev-amazon-agent-kinesis-AmazonAgentKinesisStream-2E811",
      "dataProcessingOptions": {
             "optionName": "LOGTOJSON",
             "logFormat": "SYSLOG" }
    }
                      ]
}
```

Messages just come through as plain text.  Debug level doesn't show any errors.  What's the best way to further debug this?

**Comment by mattford63** [comment]
Ah....finally found the issue.  `dataProcessingOptions` is expecting an array.

**Comment by chaochenq** [comment]
Glad that you were able to debug it through! I should have thrown a configuration exception if dataProcessingOptions takes a single element rather than an array. But since this field is optional, we don't stop the Agent from parsing and sending data (maybe we should?)

Did you get the Agent working after correcting the configuration?
