### ISSUE TITLE
Clean up files 

### ISSUE THREAD

**Issue by stevesloka** [awslabs/amazon-kinesis-agent#3]
Is there a way to have the agent clean up the files after they've been processed and sent to my delivery stream or is that on me to setup with another process?

**Comment by chaochenq** [comment]
Current we don't have the option to delete the processed files because we think customer might have their own mechanism of doing file rotation and archival. So we only grant read access to the agent on the files that need to be processed. We had an assumption of most of the use cases as below:

1. Customer generates some app log/data in their application host, and has configured rotation/retention rules for these local logs.
2. Customer somehow wants to stream these logs to S3 or Redshift in real-time, so that they can continuously monitor the data with analytic applications.

With this assumption, the agent doesn't change the existing rotation rules. However, there are already some customers requesting an option to delete processed files. So we have created a task for doing that in the future.

If you want to do that on your own, you might need to dive into the code. Another thing to keep in mind is that you need to grant the filePattern write permission to aws-kinesis-agent-user so that the agent is able to perform the deletion operation you are going to add.

**Comment by amrnablus** [comment]
@stevesloka I'm interested in adding this if it's still not ther

**Comment by AjeetDvops** [comment]
Hi Guys..
is there any way to , kinesis agent can clean up the file, after sending the data in S3.?

Or can we the generate the new files after one hour , and it will send the data from new file.
