### ISSUE TITLE
Removing successfully processed files. 

### ISSUE THREAD

**Issue by nataren** [awslabs/amazon-kinesis-agent#7]
Is there a way to configure the `aws-kinesis-agent` to delete the log files that have fully and successfully processed?

**Comment by chaochenq** [comment]
Hello, right now we don't support this mainly because Agent is not supposed to manipulate user data. We only give the agent read permission on the files. One thing that you might want to do is that you can rotate the files by using tools like logrotate, and define some retention period so that the rotated files are deleted when the period expires. Agent is able to handle the file rotation, meaning it knows to tail from the latest active file and it knows to recover/catch up from the rotated files if anything goes wrong.

But FYI, we did receive feature requests for this, and we have put it into our task queue to see if we can provide something like this.

**Comment by nataren** [comment]
Awesome, thanks a lot Chao!
