### ISSUE TITLE
Bevahior of truncatedRecordTerminator on aws-kinesis-agent

### ISSUE THREAD

**Issue by nataren** [awslabs/amazon-kinesis-agent#8]
Hi:

While reading the documentation of the `aws-kinesis-agent`, I came across the `truncatedRecordTerminator` setting.

I wanted to confirm its behavior, by:

1. setting `truncatedRecordTerminator` to `\u0000`, since each record is a valid XML file I want to make sure that by finding `\u0000` (a known invalid XML character) it means the record was truncated and I have to piece it back together in the consumer.
2. setting the `maxBufferSizeBytes` to `10` (since I know my records are larger than that, I wanted to force the truncation)

but I noticed in my kinesis consumer that all the records come across in their entirety (instead of 9 bytes at a time plus `\u0000` at a time).

Is that a behavior on the consumer side that can be relied on?

Thanks
césar

**Comment by chaochenq** [comment]
Hi,

truncatedRecordTerminator is applied to each individual record. We have a limitation on record size for both Kinesis and Firehose. For Kinesis Stream, each record is limited up to 1MB. For Kinesis Firehose, each record is limited up to 40KB.

maxBufferSizeBytes is the maximum size in bytes of the record buffer that we send in each Kinesis/Firehose putRecords API call. The agent buffers the records so that by calling Kinesis.PutRecords or Firehose.PutRecordsBatch it can send multiple records to the destination in each API call.

truncatedRecordTerminator will be applied only when your individual record exceeds our limit (1MB for Kinesis and 40KB for Firehose). Let's say you have a single record as large as 2MB, we will truncate your record to 1MB and append the truncatedRecordTerminator at the end of the truncated record.

In your case, since you set the buffer size way smaller than your record size. The expected behavior is:

1. Your record won't be truncated, because your actual Kinesis record size is not likely exceeding 1MB
2. Your record buffer will only contain 1 record, because 1) the first record will always be added to the buffer as long as the buffer is empty; 2) the second record won't be added to the buffer because the size of the records exceeds the buffer size (10 bytes in your case).
3. So you ended up having entire records delivered to your destination, possibly quite inefficiently, because each PutRecords API call only sent 1 record at once.

**Comment by nataren** [comment]
Hi @chaochenq, thanks a lot for your insightful answer.
