### ISSUE TITLE
Running Agent on windows

### ISSUE THREAD

**Issue by chaitanya-baraskar** [awslabs/amazon-kinesis-agent#80]
For my project we are using Kinesis Firehouse. I need kinesis agent for windows. Is there any way this agent will work for windows? I think as agent is written in Java it should be able to support windows platform but Just want to make sure it does. If it will work for java can you anybody tell me how so?

**Comment by chaochenq** [comment]
There’s no agent software that customer can directly use on Windows. However since Agent is written in Java and open sourced, theoretically you can download the source code and try to get it compiled and built on any platform.

It’s the bootstrapping that takes time to develop across platforms (for example, having a setup script for downloading all the dependencies, bootstrapping environment variables, users, symlinks etc). So we don’t support easy bootstrap in any other platform than RedHat Enterprise Linux, Ubuntu, and Amazon Linux for now.

Another thing is that some of the path is hardcoded in Linux convention in these setup scripts, you can refer to what we do for linux and port to Windows if anyone is interested:
https://github.com/awslabs/amazon-kinesis-agent/blob/master/bin/start-aws-kinesis-agent
https://github.com/awslabs/amazon-kinesis-agent/blob/master/bin/aws-kinesis-agent.RedHat
https://github.com/awslabs/amazon-kinesis-agent/blob/master/setup

**Comment by willwhite1** [comment]
I'll take a stab at it, I'll try and do in powershell core so it can be cross platform as well.

**Comment by willwhite1** [comment]
Attached is a PS core script which utilizes chocolatey to get ant+java.
I tested locally and the JAR is compiled successfully, however I am getting an error when trying to run it.... it's a start though.
[amazon-kinesis-agent-master.zip](https://github.com/awslabs/amazon-kinesis-agent/files/1253704/amazon-kinesis-agent-master.zip)

**Comment by laird** [comment]
Has there been any progress on this? I've got C# apps that I'd love to do event streaming via Kinesis, and In theory it should be doable via the agent, a lot more efficiently than integrating the AWS SDK, but I wouldn't want to "go it alone" in trying to getting it running.

**Comment by vijayamirtharajingit** [comment]
Now there is 
https://docs.aws.amazon.com/kinesis-agent-windows/latest/userguide/what-is-kinesis-agent-windows.html
Happy Logging !!!

**Comment by chaitanya-baraskar** [comment]
I am closing this issue Now.
