### ISSUE TITLE
Recommended way to deploy the agent.

### ISSUE THREAD

**Issue by nataren** [awslabs/amazon-kinesis-agent#9]
I am really happy with the agent, and I have been going down the path of writing multiple files from my producer to disk, and allow the agent tail them all as they show up in the directory.

After some discussions with my peers though, it seems that maybe that is the incorrect way to use the agent, and instead I should be appending new records to a single file, and then the agent will pick up the new records as they are written?

Is there a `best practices` for the agent written up somewhere, google could not find anything.

**Comment by chaochenq** [comment]
Hello,

Writing multiple files and make Agent tail them based on the filePattern is generally what we recommend. However, we hope that you use "file" here as a container of continuously generated records, rather than each file being a single record. One thing we found from some customers is that customers had use cases where they generate a huge amount of JSON files (each containing only one JSON object), and delete them once the files are processed by the Agent. The problem is that if multiple files are generated within one second, the Agent might malfunction and result in unexpected behavior and worse performance.

Getting back to the Best Practice, by design, Agent aims to help customers deliver their local data that's continuously generated by applications up to cloud in real time. One of the main use cases is listed as below. If you run into a workflow similar to this, Agent could be a perfect assistant for you.

1. Customer has a fleet of hosts where data and logs are continuously generated by the running applications into multiple local files. Each piece of data could be in the form of single-line value, CSV, JSON, or any multi-line value with pre-defined delimiters.
2. As the volume of data gets bigger and bigger, the local files could get extremely huge. Customers have also applied some rotation rules to these files, as most of the administrators would do by using tools like logrotate.
3. Customers hope that the local data could be backed up on the cloud and even loaded to data warehouses in a reliable and timely manner, which means that all the data across the fleet needs to be delivered with super low latency, and there would be no loss of a single piece of data. If any unexpected errors occurred during delivery, all the data could always be backfilled from the latest checkpoint.

Agent was designed to handle all the difficulties that one can imagine for solving these use cases. It's able to handle file rotation, checkpoint recovery, and retries upon failures to ensure all the data is delivery timely.

Feel free to let me know if you have more questions. Would always love to help. Thanks!
